# build:

#  stage: build

#  image: trion/ng-cli

#  before_script:
#   - 'which ssh-agent || ( apt-get install -qq openssh-client )'
#   - eval $(ssh-agent -s)
#   - ssh-add <(echo "$SSH_PRIVATE_KEY")
#   - mkdir -p ~/.ssh
#   - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
#   - cd impc-publication-curation-client/
#   - npm ci

#  script:

#   - npm run build-infrafrontier
#   - export SCP_ROUTE=$DEPLOYMENT_USER
#   - SCP_ROUTE+="@"
#   - SCP_ROUTE+=$DEPLOYMENT_SERVER
#   - SCP_ROUTE+=":"
#   - SCP_ROUTE+=$DEPLOYMENT_PATH
#   - scp -o StrictHostKeyChecking=no -r dist/impc-publication-curation-client/* $SCP_ROUTE